[project]
name = "fantasy-nba-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]>=0.120.0",
    "httpx>=0.28.1",
    "ortools>=9.14.6206",
    "pulp>=3.3.0",
    "typing>=3.10.0.0",
]
